name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: ${project.version}
description: Core plugin for the KoolFreedom SMP
depend: [ ProtocolLib, WorldGuard, LuckPerms ]
softdepend: [ Essentials, DiscordSRV ]
authors: [gamingto12]
commands:
  adminchat:
    usage: /<command> <message>
    description: Speak with other staff members
    permission: kf.admin
    aliases: [ o, oc, adminchat, ac ]
  ban:
    description: Ban someone
    usage: /<command> <player> [reason]
    aliases: [gtfo]
    permission: kf.admin
  banip:
    description: Ban an IP address
    usage: /<command> <ip> [reason]
    aliases: [ ban-ip ]
    permission: kf.admin
  banlist:
    description: Manage the ban list
    usage: /banlist [reload]
    permission: kf.admin
  clearchat:
    description: Clears the chat
    aliases: [cc]
    permission: kf.admin
  commandspy:
    description: Spy on another player's commands.
    aliases: [cmdspy, cspy]
    permission: kf.admin
  crash:
    description: Crash a person's client
    permission: kf.exec
  cry:
    description: womp womp
  doom:
    description: Ban someone with excessive violence
    usage: /doom <player> [reason]
    aliases: [obliterate]
    permission: kf.senior
  hug:
    descriptions: Hug a player
    usage: /hug <player>
  kick:
    description: Kick someone
    usage: /kick <player>
    permission: kf.admin
  kiss:
    description: For the lovebirds, give em a big ol kiss
    usage: /kiss <player>
  koolsmpcore:
    description: Display information about the plugin
    aliases: [kfc]
    usage: /kfc [reload]
  mute:
    description: Mutes a player
    usage: /mute <player>
    permission: kf.admin
  orbit:
    description: trol
    usage: /orbit <user> <<power> | stop>
    permission: kf.admin
  pat:
    description: pat pat
  permbans:
    description: Reload the PermBans configuration file.
    usage: /permbans <reload>
    permission: kf.senior
  poke:
    description: poke
  rawsay:
    description: Tellraw...but better
    usage: /rawsay <message>
    permission: kf.admin
  report:
    description: Report a suspicious user
    usage: /report <player> <reason>
  satisfyall:
    description: Feed and heal everyone online
    usage: /<command>
    permission: kf.admin
  say:
    description: what the fuck else does it do
    usage: /say <message>
    permission: kf.admin
  ship:
    description: Make a really unfunny joke about how you ship 2 people.
    usage: /ship <player1> <player2>
  slap:
    description: Slap the shit out of someone
    usage: /slap <player>
  smite:
    description: Smite that motherfucker
    usage: /smite <player> [reason]
    permission: kf.admin
    permission-message: kf.admin
  spectate:
    description: Suspicious user? Spectate them
    usage: /spectate <player>
    permission: kf.admin
  unban:
    description: Unban someone
    usage: /unban <player>
    permission: kf.admin
  warn:
    description: Warn someone
    usage: /warn <player> [reason]
    permission: kf.admin
permissions:
  kf.admin:
    default: op
  kf.senior:
    default: op
  kf.exec:
    default: op
libraries:
  - org.apache.commons:commons-lang3:3.17.0